In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# !ls drive/MyDrive/NCSUFall23/ALDA/Project/OIL

GC			   oil_merge_13.csv  Oil_methods_RMSE.xlsx  Taiyo
LSTMModelTimeSeries.ipynb  oil_merge_13.xls  OilModelALDA.ipynb


In [4]:
# %cd drive/MyDrive/NCSUFall23/ALDA/Project/OIL

/content/drive/MyDrive/NCSUFall23/ALDA/Project/OIL


## Load data

In [5]:
df = pd.read_csv('data/oil_data.csv',parse_dates=['Date'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4704 entries, 0 to 4703
Data columns (total 14 columns):
 #   Column                                                    Non-Null Count  Dtype         
---  ------                                                    --------------  -----         
 0   Date                                                      4704 non-null   datetime64[ns]
 1   WTI_dollar_per_barrel                                     4704 non-null   float64       
 2   copper_close                                              4704 non-null   float64       
 3   dji_index                                                 4704 non-null   float64       
 4   gold_close                                                4704 non-null   float64       
 5   eur_close                                                 4704 non-null   float64       
 6   Henry Hub Natural Gas Spot Price Dollars per Million Btu  4704 non-null   float64       
 7   rub_close                                 

In [7]:
df['Date'].max()

Timestamp('2021-12-31 00:00:00')

In [8]:
df.shape

(4704, 14)

In [9]:
df.columns

Index(['Date', 'WTI_dollar_per_barrel', 'copper_close', 'dji_index',
       'gold_close', 'eur_close',
       'Henry Hub Natural Gas Spot Price Dollars per Million Btu', 'rub_close',
       'silver_close', 'nasdaq_close', 'SP500', 'pal_close', 'corn_close',
       'heat_close'],
      dtype='object')

## Preprocessing

In [10]:
df = df.iloc[:,1:]

In [11]:
df.columns

Index(['WTI_dollar_per_barrel', 'copper_close', 'dji_index', 'gold_close',
       'eur_close', 'Henry Hub Natural Gas Spot Price Dollars per Million Btu',
       'rub_close', 'silver_close', 'nasdaq_close', 'SP500', 'pal_close',
       'corn_close', 'heat_close'],
      dtype='object')

In [12]:
X = df.iloc[:,1:]

In [13]:
X.columns

Index(['copper_close', 'dji_index', 'gold_close', 'eur_close',
       'Henry Hub Natural Gas Spot Price Dollars per Million Btu', 'rub_close',
       'silver_close', 'nasdaq_close', 'SP500', 'pal_close', 'corn_close',
       'heat_close'],
      dtype='object')

In [14]:
Y = df.iloc[:,0]

In [15]:
Y

0       29.89
1       30.74
2       30.61
3       31.24
4       30.68
        ...  
4699    75.49
4700    76.01
4701    76.58
4702    76.83
4703    75.33
Name: WTI_dollar_per_barrel, Length: 4704, dtype: float64

## Selecting features

In [16]:
X.columns

Index(['copper_close', 'dji_index', 'gold_close', 'eur_close',
       'Henry Hub Natural Gas Spot Price Dollars per Million Btu', 'rub_close',
       'silver_close', 'nasdaq_close', 'SP500', 'pal_close', 'corn_close',
       'heat_close'],
      dtype='object')

In [19]:
selected_features = ['gold_close','eur_close','Henry Hub Natural Gas Spot Price Dollars per Million Btu', 'rub_close', 'SP500', 'heat_close']

In [20]:
X_selected = df[selected_features]

In [21]:
X_selected.columns

Index(['gold_close', 'eur_close',
       'Henry Hub Natural Gas Spot Price Dollars per Million Btu', 'rub_close',
       'SP500', 'heat_close'],
      dtype='object')

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X_selected)

In [23]:
X_normalized

array([[0.01842924, 0.62412829, 0.16378162, 0.35267048, 0.11935685,
        0.        ],
       [0.01908978, 0.5986942 , 0.18286729, 0.3525488 , 0.11829547,
        0.00874084],
       [0.01922188, 0.59180893, 0.18286729, 0.3525488 , 0.11772232,
        0.00984107],
       ...,
       [0.72911025, 0.85119465, 0.0918775 , 0.97590762, 0.98149557,
        0.063478  ],
       [0.72911025, 0.85119465, 0.11051931, 0.97590762, 0.98149557,
        0.063478  ],
       [0.72911025, 0.85119465, 0.11051931, 0.97590762, 0.98149557,
        0.063478  ]])

## Split Data into training and testing dataset

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_selected, Y, test_size=0.2, random_state=42)

In [26]:
X_train_normalized, X_test_normalized, y_train_normalized, y_test_normalized = train_test_split(X_normalized, Y, test_size=0.2, random_state=42)

In [27]:
X_train

gold_close  eur_close  \
3194  1219.800049    0.90703   
3783  1300.099976    0.85710   
1200   927.299988    0.63613   
4108  1526.500000    0.90205   
1344   895.299988    0.77131   
...           ...        ...   
4426  1478.599976    0.91228   
466    446.100006    0.81433   
3092  1149.000000    0.88747   
3772  1290.199951    0.84596   
860    653.099976    0.75115   

      Henry Hub Natural Gas Spot Price Dollars per Million Btu  rub_close  \
3194                                               1.78         75.180000   
3783                                               2.94         62.097000   
1200                                              12.96         23.476999   
4108                                               2.36         66.745102   
1344                                               4.75         32.625999   
...                                                 ...               ...   
4426                                               2.23         80.919998   
466                                               10.71         28.410000   
3092                                               2.35         63.391499   
3772                                               2.85         62.236000   
860                                                6.70         26.032000   

            SP500  heat_close  
3194  1948.050049      1.0512  
3783  2705.270020      2.1914  
1200  1252.310059      3.9696  
4108  2924.580078      1.8640  
1344   831.950012      1.4505  
...           ...         ...  
4426  3577.590088      1.0417  
466   1231.199951      1.8402  
3092  1995.829956      1.5796  
3772  2722.459961      2.2692  
860   1402.060059      1.6884  

[3763 rows x 6 columns]

In [28]:
X_train_normalized

array([[0.55816109, 0.83561359, 0.01997337, 0.9060642 , 0.38559068,
        0.06638143],
       [0.61120286, 0.68743144, 0.07146028, 0.74687224, 0.61521897,
        0.41485332],
       [0.36495146, 0.03163672, 0.51620062, 0.27694994, 0.17460631,
        0.95831296],
       ...,
       [0.51139443, 0.7775635 , 0.04527297, 0.7626235 , 0.40008003,
        0.22787286],
       [0.60466344, 0.65437019, 0.0674656 , 0.74856357, 0.62043185,
        0.43863084],
       [0.18382984, 0.37299311, 0.23834887, 0.3080388 , 0.22001826,
        0.26112471]])

## Building Model

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [30]:
knn_regressor = KNeighborsRegressor(n_neighbors=10)
knn_regressor.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=10)

In [31]:
rf_model = RandomForestRegressor(n_estimators=128)
rf_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=128)

In [32]:
rf_pred = rf_model.predict(X_test)

In [33]:
knn_pred = knn_regressor.predict(X_test)

In [34]:
ensemble_pred = (rf_pred + knn_pred) / 2

In [35]:
# ensemble_pred

## Results

In [36]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, ensemble_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 10.160861501795875


In [37]:
mse_rf = mean_squared_error(y_test, rf_pred)
print(f'Mean Squared Error: {mse_rf}')

Mean Squared Error: 3.6806585330227275


In [38]:
mse_knn = mean_squared_error(y_test, knn_pred)
print(f'Mean Squared Error: {mse_knn}')

Mean Squared Error: 32.125074420120434


## Normalized Model

In [39]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [40]:
knn_regressor = KNeighborsRegressor(n_neighbors=10)
knn_regressor.fit(X_train_normalized, y_train_normalized)

KNeighborsRegressor(n_neighbors=10)

In [41]:
rf_model = RandomForestRegressor(n_estimators=128)
rf_model.fit(X_train_normalized, y_train_normalized)

RandomForestRegressor(n_estimators=128)

In [42]:
rf_pred_normalized = rf_model.predict(X_test_normalized)
knn_pred_normalized = knn_regressor.predict(X_test_normalized)

In [43]:
ensemble_pred_normalized = (rf_pred_normalized + knn_pred_normalized) / 2

## Results normalized

In [44]:
y_test_normalized[:3]

4622    69.34
3483    51.69
1292    55.95
Name: WTI_dollar_per_barrel, dtype: float64

In [45]:
ensemble_pred_normalized[:3]

array([79.64913281, 52.03251953, 57.94896094])

In [49]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test_normalized, ensemble_pred_normalized)
print(f'Mean Squared Error of ensember: {mse}')

Mean Squared Error of ensember: 3.315726176927537


In [50]:
mse_rf = mean_squared_error(y_test_normalized, rf_pred_normalized)
print(f'Mean Squared Error of random forest: {mse_rf}')

Mean Squared Error of random forest: 3.6439553855683626


In [51]:
mse_knn = mean_squared_error(y_test_normalized, knn_pred_normalized)
print(f'Mean Squared Error of KNN: {mse_knn}')

Mean Squared Error of KNN: 4.099818011099303
